title: The Lounge &mdash; Self-hosted web IRC client
description: "The official website for The Lounge, the self-hosted web IRC client."
baseurl: ""
include:
  - _headers
  - _redirects
plugins:
  - jekyll-sitemap
collections:
  docs:
    output: true
  guides:
    output: true
    permalink: /docs/:collection/:path:output_ext
