title: The Lounge &mdash; Self-hosted web IRC client
description: "The official website for The Lounge, the self-hosted web IRC client."
baseurl: ""
include:
  - _headers
  - _redirects
kramdown:
  toc_levels: "2"
plugins:
  - jekyll-sitemap
collections:
  docs:
    output: true
  api:
    output: true
    permalink: /docs/:collection/:path:output_ext
  guides:
    output: true
    permalink: /docs/:collection/:path:output_ext
