title: The Lounge &mdash; Self-hosted web IRC client
description: "The official website for The Lounge, the self-hosted web IRC client."
include:
  - _headers
  - _redirects
kramdown:
  toc_levels: "2"
url: https://thelounge.chat # Domain used by jekyll-sitemap in sitemap.xml
plugins:
  - jekyll-sitemap
permalink: /:path
collections:
  docs:
    output: true
  api:
    output: true
    permalink: /docs/:collection/:path
  guides:
    output: true
    permalink: /docs/:collection/:path
